Solve `pygit2` version conflict
In version 1.5.0, I got a 
> ImportError: cannot import name 'GIT_MERGE_PREFERENCE_FASTFORWARD_ONLY' from 'pygit2'

`GIT_MERGE_PREFERENCE_FASTFORWARD_ONLY` was introduced in 1.6.0. Upgrade the min version of `pygit2` to fix it.